POST http://localhost:3003/api/blogs
Content-Type: application/json
# add Authorization: bearer {token}

{
  "url": "www.google.com",
  "title": "first blog of some user",
  "author": "a random user",
  "likes": 3,
  "userId": "622e4d2fc9756ef621a2e992"
}
