POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyMmU0ZDJmYzk3NTZlZjYyMWEyZTk5MiIsImlhdCI6MTY0NzIwNTc3MCwiZXhwIjoxNjQ3MjA5MzcwfQ.cw8o5kBgvRrD-QTQeSamlBrKK7uEe6iaqdOLRlOIEe8

{
  "url": "www.google.com",
  "title": "first blog of some user",
  "author": "a random user",
  "likes": 3,
  "userId": "622e4d2fc9756ef621a2e992"
}
