POST http://localhost:3001/api/notes
Content-Type: application/json
# add Authorization: bearer {token}

{
  "content": "second note for the first user",
  "important": true,
  "userId": "622e4106b812f6b9e5e0bcec"
}
